export const CURRENT_GAME_SITUATION = "CURRENT_GAME_SITUATION";
export const IS_GAME_STARTED = "IS_GAME_STARTED";
export const ADD_PLAYER_PICKS = "ADD_PLAYER_PICKS";
export const RESET_GAME = "RESET_GAME";
